AdnLike/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.home, name='home'),
                  path('login-error/', views.error, name='error'),
                  path('accounts/', include('accounts.urls')),
                  path('homepage/', include('homepage.urls')),
                  path('influencer/', include('influencer.urls')),
                  path('advertisement/', include('advertisement.urls')),
                  path('oauth/', include('social_django.urls', namespace='social')),
                  path('brand/', include('brand.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

brand/urls.py
from django.urls import path
from . import views

app_name = 'brand'

urlpatterns = [
    path('', views.BrandHomePage.as_view(), name='brand_home'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:pk>/settings/account', views.SettingAccountView.as_view(), name='settings_account'),
    path('<int:pk>/settings/profile', views.SettingProfileView.as_view(), name='settings_profile'),
    path('settings/password/', views.password, name='password'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User, Group


class City(models.Model):
    id = models.AutoField(primary_key=True)
    city_name = models.TextField(max_length=20, unique=True, verbose_name='City')
    insert_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = 'accounts'
        ordering = ['insert_date']

    def __str__(self):
        return self.city_name


class Country(models.Model):
    id = models.AutoField(primary_key=True)
    country_name = models.TextField(max_length=20, unique=True, verbose_name='Country')
    insert_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = 'accounts'
        ordering = ['insert_date']

    def __str__(self):
        return self.country_name


class UserProfile(models.Model):
    MALE = 'MALE'
    FEMALE = 'FEMALE'
    GENDER_CHOICES = ((MALE, 'Male'),
                      (FEMALE, 'Female'))

    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    city = models.ForeignKey('accounts.City', on_delete=models.SET_NULL, null=True)
    country = models.ForeignKey('accounts.Country', on_delete=models.SET_NULL, null=True)
    birthday = models.DateField(null=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, null=True)
    timezone = models.IntegerField(null=True)
    verified = models.NullBooleanField()

    insert_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user)

    class Meta:
        app_label = 'accounts'
        ordering = ['user']

homepage/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from accounts.models import UserProfile


class SettingsAccountForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class SettingsProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['birthday'].widget.attrs.update({'autocomplete': 'off'})

    class Meta:
        model = UserProfile
        fields = ['country', 'city', 'birthday', 'gender', ]

homepage/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, redirect
from django.contrib.messages import get_messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from accounts.models import UserProfile
from .forms import SettingsAccountForm, SettingsProfileForm
from django.contrib.auth import get_user_model

from social_django.models import UserSocialAuth

User = get_user_model()


def home(request):
    if not request.user.is_authenticated:
        return render(request, 'homepage/home.html')
    else:
        if request.user.groups.all()[0].name == 'influencer':
            return redirect('influencer:ad_recommend_list')
        elif request.user.groups.all()[0].name == 'brand':
            return redirect('brand:brand_home')
        else:
            return render(request, 'homepage/home.html')


def error(request):
    # storage = get_messages(request)
    # for message in storage:
    #     if 'social-auth' in message.tags and 'error' in message.level_tag:
    return render(request, 'homepage/error.html')


class SettingAccountView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/'
    redirect_field_name = '/'

    form_class = SettingsAccountForm
    template_name = 'homepage/settings_account.html'
    model = User

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse_lazy('homepage:settings_account', kwargs={'pk': pk})


class SettingProfileView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/'
    redirect_field_name = '/'

    form_class = SettingsProfileForm
    template_name = 'homepage/settings_profile.html'
    model = UserProfile

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj

    def get_queryset(self):
        user_id = self.request.user.id
        return UserProfile.objects.filter(user_id__exact=user_id)

    def get_success_url(self):
        pk = self.kwargs.get('pk')
        return reverse_lazy('homepage:settings_profile', kwargs={'pk': pk})


@login_required
def settings(request):
    user = request.user

    try:
        twitter_login = user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None

    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    return render(request, 'homepage/settings_account.html', {
        'twitter_login': twitter_login,
        'facebook_login': facebook_login,
        'can_disconnect': can_disconnect
    })


@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('homepage:settings')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'homepage/password.html', {'form': form})

homepage/templates/homepage/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2><strong>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags %}
                    <li>{{ message }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
</strong></h2>
</body>
</html>

homepage/templates/homepage/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AdnX</title>
</head>
<body>
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <a>WELCOME !!!!</a>
        </div>
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/pK7Jdj6geu8"
                            allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <a>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                            exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure
                            dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                            Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                            mollit anim id est laborum.</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


</body>
</html>

homepage/templates/homepage/password.html
{% extends 'base.html' %}

{% block content %}
  <h2>Change Password</h2>
  {% if not user.has_usable_password %}
    <p style="color: red">You have not defined a password yet.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
{% endblock %}

homepage/templates/homepage/settings_account.html
{% extends 'homepage/settings_base.html' %}
{% load bootstrap4 %}

{% block settings %}

    <div class="col-9">
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-account" role="tabpanel"
                 aria-labelledby="v-pills-account-tab">
                <h1>Account</h1>
                <h2>WELCOME {{ user.username }}</h2>

                <form method="post">{% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">Update</button>
                    {% endbuttons %}
                </form>

                <h3>Facebook</h3>
                {% if facebook_login %}
                    <p>Connected as <a href="https://facebook.com/{{ facebook_login.extra_data.id }}/"
                                       target="_blank">{{ facebook_login.extra_data.id }}</a></p>
                    {% if can_disconnect %}
                        <form method="post" action="{% url 'social:disconnect' 'facebook' %}">
                            {% csrf_token %}
                            <button type="submit">Disconnect from Facebook</button>
                        </form>
                    {% else %}
                        <button type="button" disabled>Disconnect from Facebook</button>
                        <p style="color: red">You must <a href="{% url 'homepage:password' %}">define a
                            password</a> for
                            your account before disconnecting from Facebook.</p>
                    {% endif %}
                {% else %}
                    <a href="{% url 'social:begin' 'facebook' %}">Connect to Facebook</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

homepage/templates/homepage/settings_base.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    <div class="row">
        <div class="col-3">
            <nav class="nav flex-column nav-pills">
                <a class="nav-link" href="{% url 'homepage:settings_account' user.pk %}">Account</a>
                <a class="nav-link" href="#">Password</a>
                <a class="nav-link" href="{% url 'homepage:settings_profile' user.pk %}">Profile</a>
            </nav>
        </div>
        {% block settings %}
        {% endblock %}
    </div>

{% endblock %}

homepage/templates/homepage/settings_profile.html
{% extends 'homepage/settings_base.html' %}
{% load bootstrap4 %}
{% block settings %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_birthday").datepicker();
        });

        $(function () {

            $("#id_birthday").autocomplete({
                source: availableTags,
                minLength: 0
            }).keyup(function (e) {
                if (e.which === 13) {
                    $(".ui-menu-item").hide();
                }
            });
        });

    </script>
    <div class="col-9">
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-account" role="tabpanel"
                 aria-labelledby="v-pills-account-tab">
                <h1>Profile</h1>

                <form method="post">{% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">Update</button>
                    {% endbuttons %}
                </form>

            </div>
        </div>
    </div>

{% endblock %}