AdnLike/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', views.home, name='home'),
                  path('login-error/', views.error, name='error'),
                  path('accounts/', include('accounts.urls')),
                  path('homepage/', include('homepage.urls')),
                  path('influencer/', include('influencer.urls')),
                  path('advertisement/', include('advertisement.urls')),
                  path('oauth/', include('social_django.urls', namespace='social')),
                  path('brand/', include('brand.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advertisement/urls.py
from django.urls import path
from . import views

app_name = 'advertisement'

urlpatterns = [
    path('publish/<slug:slug_name>/<int:pk>/',
         views.PublishAdvertisement.as_view(), name='publish'),
    path('delete/<slug:slug_name>/<int:pk>/',
         views.DeleteAdvertisement.as_view(), name='delete'),
]

brand/urls.py
from django.urls import path
from . import views

app_name = 'brand'

urlpatterns = [
    path('', views.BrandHomePage.as_view(), name='brand_home'),
]

advertisement/models.py
import uuid

from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone


User = get_user_model()


def user_directory_path(instance, filename):
    my_custom_date = timezone.now().date()
    return 'advertisement_image/{0}/user_{1}/{2}'.format(my_custom_date, instance.username.id, filename)


class AdvStats(models.Model):
    id = models.AutoField(primary_key=True)
    guid = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    adv_id = models.OneToOneField('advertisement.AdvSummary', related_name='adv_stats', on_delete=models.SET_NULL,
                                  null=True)
    username = models.ForeignKey(User, related_name='adv_stats', on_delete=models.SET_NULL, null=True)
    number_of_likes = models.IntegerField(verbose_name='Number Of Likes', null=True, default=0)


class AdvImages(models.Model):
    summary = models.ForeignKey('advertisement.AdvSummary', related_name='adv_images', on_delete=models.SET_NULL,
                                null=True)
    advertisement_image = models.ImageField(upload_to=user_directory_path,
                                            verbose_name='Advertisement Image',
                                            null=True, blank=True)


class AdvSummary(models.Model):
    id = models.AutoField(primary_key=True)
    guid = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
    username = models.ForeignKey(User, related_name='advertisements', on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey('brand.Brand', related_name='brand', null=True, on_delete=models.SET_NULL)
    slug_name = models.CharField(max_length=100, null=False, default='')
    categories = models.ManyToManyField('advertisement.Category')
    name = models.CharField(max_length=255)
    budget = models.DecimalField(max_digits=38, decimal_places=2)
    max_fee_per_like = models.IntegerField()
    expire_date = models.DateField()
    adv_desc = models.CharField(max_length=255, verbose_name='Advertisement Description', null=True)
    adv_min_follower = models.IntegerField(verbose_name='Advertisement Minimum Follower', null=True)
    adv_max_follower = models.IntegerField(verbose_name='Advertisement Maximum Follower', null=True)
    is_approved = models.BooleanField(null=False, default=0)

    create_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = 'advertisement_summary'
        ordering = ['-publish_date']

    def __str__(self):
        return self.name

    def publish(self):
        self.publish_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('advertisement:publish', kwargs={'slug_name': self.slug_name,
                                                        'pk': self.pk})


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False)

    insert_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

brand/models.py
from django.db import models
from django.contrib.auth import get_user_model
from advertisement.models import AdvSummary

User = get_user_model()


class Brand(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=False)
    username = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    insert_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

brand/forms.py
from django.forms import ModelForm
from advertisement.models import AdvSummary
from django.utils.translation import ugettext_lazy as _
import datetime
from django import forms


class AdvertisementSoftForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control form-control-lg', 'placeholder': 'Advertisement Name', 'autocomplete': 'off'})
        self.fields['budget'].widget.attrs.update(
            {'class': 'form-control form-control-lg', 'placeholder': 'Advertisement Budget', 'autocomplete': 'off'})
        self.fields['max_fee_per_like'].widget.attrs.update(
            {'class': 'form-control form-control-lg', 'placeholder': 'Advertisement Max Fee Per Like',
             'autocomplete': 'off'})
        self.fields['expire_date'].widget.attrs.update({'class': 'form-control form-control-lg', 'autocomplete': 'off'})

    class Meta:
        model = AdvSummary
        fields = ['name', 'budget', 'max_fee_per_like', 'expire_date']

    def clean_expire_date(self):
        data = self.cleaned_data['expire_date']

        if data < datetime.date.today():
            raise forms.ValidationError(_('Invalid Date - Expire Date must be bigger than Today'))

        return data

brand/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from advertisement.models import AdvSummary
from django.utils.text import slugify
from .forms import AdvertisementSoftForm
from django.utils import timezone
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

User = get_user_model()


class CreateAdvertisement(generic.CreateView):
    form_class = AdvertisementSoftForm
    template_name = 'brand/advertisement_brand_home.html'
    context_object_name = 'create_advertisement_form'
    model = AdvSummary

    def form_valid(self, form):
        new_adv = form.save(commit=False)
        new_adv.slug_name = slugify(new_adv.name + "_" + str(new_adv.guid))
        new_adv.username = self.request.user
        new_adv.save()
        return super().form_valid(form)


class PublishedAdvertisementList(generic.ListView):
    model = AdvSummary
    paginate_by = 3
    template_name = 'brand/advertisement_brand_home.html'
    context_object_name = 'advertisement_list'

    def get_queryset(self):
        return AdvSummary.objects.filter(username__exact=self.request.user).filter(expire_date__gte=timezone.now()).\
            filter(publish_date__isnull=False).order_by('-publish_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_advertisement_form'] = AdvertisementSoftForm()
        #context['is_paginated'] = True
        unpublished_advertisement_list = AdvSummary.objects.filter(username__exact=self.request.user).\
            filter(expire_date__gte=timezone.now()). \
            filter(publish_date__isnull=True).order_by('create_date')
        # paginator = Paginator(unpublished_advertisement_list, 3)
        # page = self.request.GET.get('page')
        context['unpublished_advertisement_list'] = unpublished_advertisement_list

        context['top5_advertisement_list'] = AdvSummary.objects.filter(expire_date__gte=timezone.now()). \
            filter(publish_date__isnull=False).order_by('adv_stats__number_of_likes')

        return context


class BrandHomePage(LoginRequiredMixin, generic.View):
    login_url = '/'
    redirect_field_name = '/'

    def post(self, request, *args, **kwargs):
        view = CreateAdvertisement.as_view()
        return view(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        view = PublishedAdvertisementList.as_view()
        return view(request, *args, **kwargs)

brand/templates/brand/advertisement_brand_home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_expire_date").datepicker();
        });

        $(function () {

            $("#id_expire_date").autocomplete({
                source: availableTags,
                minLength: 0
            }).keyup(function (e) {
                if (e.which === 13) {
                    $(".ui-menu-item").hide();
                }
            });
        });

    </script>
    <h2>Create New Advertisement</h2>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            {% for field in create_advertisement_form %}
                <div class="col-lg-6 col-md-12 col-sm-12 ">
                    <table class="table table-borderless">
                        <tbody>
                        <tr>
                            <td><h3>{{ field.label_tag }}</h3></td>
                        </tr>
                        <tr>
                            <td>{{ field }}</td>
                        </tr>
                        <tr>
                            <td><span style="color:red">{{ field.errors }}</span></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            {% endfor %}
            <table class="table table-borderless">
                <tbody>
                <tr>
                    <td><input type="submit" class="btn btn-primary btn-lg" value="Create Adv"/></td>
                </tr>
                </tbody>
            </table>
        </div>
    </form>


    <h2>Un-published Advertisements</h2>
    {% if unpublished_advertisement_list %}

        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Advertisement Name</th>
                <th scope="col">Budget</th>
                <th scope="col">Max Fee Per Like</th>
            </tr>
            </thead>
            <tbody>
            {% for adv in unpublished_advertisement_list %}
                <tr>
                    <td>{{ adv.name }}</td>
                    <td>{{ adv.budget }}</td>
                    <td>{{ adv.max_fee_per_like }}</td>
                    <td><a href="{% url 'advertisement:publish' adv.slug_name adv.pk %}" class="see_detail">continue</a></td>
                    <td><a href="{% url 'advertisement:delete' adv.slug_name adv.pk %}" class="delete">delete</a></td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
        {# .... **Now the pagination section** .... #}
        {% if is_paginated %}
            <nav aria-label="Search results pages">
                <ul class="pagination justify-content-center">
                    {% if unpublished_advertisement_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="/brand?page={{ unpublished_advertisement_list.previous_page_number }}"
                               tabindex="-1">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#"
                               tabindex="-1">&laquo;</a>
                        </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if paginator.number == i %}
                            <li class="page-item active"><a class="page-link">{{ i }} <span
                                    class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if unpublished_advertisement_list.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="/brand?page={{ unpublished_advertisement_list.next_page_number }}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#"
                               tabindex="-1">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    {% else %}
        <h3>Advertisement List</h3>
        <p>No Advertisement found!!!</p>
    {% endif %}















    <h2>Your Current Ads</h2>
    {% if advertisement_list %}

        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Advertisement Name</th>
                <th scope="col">Number of Likes</th>
                <th scope="col">Number of Influencer</th>
                <th scope="col">Expire Date</th>
            </tr>
            </thead>
            <tbody>
            {% for adv in advertisement_list %}
                <tr>
                    <td>{{ adv.name }}</td>
                    <td>0</td>
                    <td>0</td>
                    <td>{{ adv.expire_date }}</td>
                    <td><a href="/advertisement/{{ adv.id }}/" class="see_detail">detail</a></td>
                    <td><a href="{% url 'advertisement:delete' adv.slug_name adv.pk %}" class="delete">delete</a></td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
        {# .... **Now the pagination section** .... #}
        {% if is_paginated %}
            <nav aria-label="Search results pages">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="/brand?page={{ page_obj.previous_page_number }}"
                               tabindex="-1">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#"
                               tabindex="-1">&laquo;</a>
                        </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active"><a class="page-link">{{ i }} <span
                                    class="sr-only">(current)</span></a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="/brand?page={{ page_obj.next_page_number }}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#"
                               tabindex="-1">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    {% else %}
        <h3>Advertisement List</h3>
        <p>No Advertisement found!!!</p>
    {% endif %}
{% endblock %}